version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - FORTIFY_VIEWS=true
      - FORTIFY_FEATURES=login,registration,password-reset,email-verification
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS="hello@example.com"
      - MAIL_FROM_NAME="${APP_NAME}"

volumes:
  db_data:
