FROM php:8.2-apache

# Instala extensões PHP necessárias
RUN apt-get update && apt-get install -y \
    git unzip zip curl libpng-dev libonig-dev libxml2-dev libzip-dev \
    && docker-php-ext-install pdo pdo_mysql zip

# Ativa o mod_rewrite do Apache (essencial para Laravel)
RUN a2enmod rewrite

# Define o diretório de trabalho
WORKDIR /var/www/html

# Instala Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copia arquivos (será sobrescrito por volume)
COPY ./src /var/www/html

# Permissões para Laravel
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html
